#!/usr/bin/env python
from hmi.grammar_parser import GrammarParser
import argparse
import os


def read_valid_file(p, arg):
    if not os.path.exists(arg):
        p.error("The file %s does not exist!" % arg)
    else:
        return open(arg, 'r').read()

parser = argparse.ArgumentParser()
parser.add_argument("target", type=str)
parser.add_argument("--grammar", type=str)
parser.add_argument("--grammar-file", type=lambda x: read_valid_file(parser, x))
args = parser.parse_args()

# Verify the specified grammar
if (args.grammar_file and args.grammar) or (args.grammar_file is None and args.grammar is None):
    parser.error("Please specify either a grammar string using --grammar of a grammar file using --grammar-file")

grammar = args.grammar_file if args.grammar_file else args.grammar

print "Parsing grammar:\n\n{}\n\n".format(grammar)

grammar_parser = GrammarParser.fromstring(grammar)

print "BNF grammar:\n\n{}\n\n".format(grammar_parser.to_bnf_grammar(args.target))
